### ISSUE TITLE
baisiclly the mods for the modpack are not loading for me 

### ISSUE THREAD

**Issue by kyable** [benbenlaw/techopolis#17]
im not to good with code but in the discord i was told to come here to try to get help and ive been told that the mods arent loading and as far as im aware im missing this line of code
Reloading ResourceManager: KubeJS Virtual Data Pack
i run on java 8 and the mod version is B9

**Comment by CharZinta** [comment]
I tried to assist the user as much as possible. When Launching the client the user gets to the loading FML screen, then it loads no mods and switches to vanilla, their words. Trying to compare a clean B8 start the only thing I couldn't get them to find in their log file was anything about KUBEJS.

User is running B8 and has tried to reinstall with Curse and GDL a couple of times.
@kyable  you should post your java version

**Comment by thaimichael** [comment]
![image](https://user-images.githubusercontent.com/6601697/153028077-64f01a34-2a1f-4598-bbd2-b79b3f0de7d8.png)
There has been an issue with the curseforge API which has caused the mods to not download correctly when using the GDLauncher.  It took me 2 days to finally get the pack update downloaded fully.  Above is a clip of the announcement on the GDLauncher Discord.  I can verify 2 days ago still having issues with downloading modpacks off curseforge sometimes it works sometimes does not complete.  Just kept restarting the GDLauncher and selecting repair until the repair was completed successfully worked for me.  If the GDLauncher hangs during the download process and you restart the launcher you can run the pack but it will be vanilla with forge no mods loaded since the mods folder is empty.  Hope this helps with this issue.
