### ISSUE TITLE
How to start server in skyblock mode?

### ISSUE THREAD

**Issue by CarlSmotricz** [benbenlaw/techopolis#23]
Question says it all. Downloaded and ran the server pack from CurseForge; the generated world is a standard overworld.

What do I need to change to make it skyblock? Setting `level-type=skyblock` in server.properties didn't do it.

**Comment by LotP1** [comment]
please read the FAQ on the discord server :)

**Comment by AL1L** [comment]
You say that, but I did all the stuff that it says and it never worked. I ended up just making a skyblock world in singleplayer and importing it into the server

**Comment by CarlSmotricz** [comment]
I don't like Discord and I'm unwilling to join up just to get an answer to what I consider a straightforward FAQ.

**Comment by AL1L** [comment]
Here's straight from their Discord server

> Singleplayer, choose a new world and choose world type skyblock for servers use information above. Once in game there is a checkbox quest that will reward you with the skyblock recipes. Ones recipes are enabled restart your world or server and you will be ready to go!
Clay can be made in a pulversizer (ENABLE SKYBLOCK MODE RECIPES)
Servers can add the pinned file to have skyblock mode automatically enabled without clients needing to change anything

`skyblockMode.json`:
```json
{
	"enableSkyblockMode": true,
	"message": "True enables skyblock mode recipes."
}
```

**Comment by LotP1** [comment]
Here's the full server setup info:

Servers (See rules-and-faq to see server setup instructions)

To make new islands/spheres for other players on a server, you have to set up a command block or make a config change in order to use the following command.
/skyblock create <TeamName> <PlayerName>
The config you need to change is 
Techopolis\config\skyblockbuilder\common-config.json5
create-own-team = true
This config change allows all players to make new islands, so use with caution. Wouldn't be a good idea for public servers.
The server world types:
level-type=skyblockbuilder\\:custom_skyblock (Skyblock mode, enable skyblock recipes in game)
level-type=hexlands:hexlands (Hexlands)
level-type=hexlands:hexlands_overworld_only (Hexlands, overworld only)
level-type=default (Default Minecraft World Gen)
level-type=terraforged (Terraforged World Gen)

Skyblock Mode

Singleplayer, choose a new world and choose world type skyblock for servers use information above. Once in game there is a checkbox quest that will reward you with the skyblock recipes. Ones recipes are enabled restart your world or server and you will be ready to go!
Clay can be made in a pulversizer (ENABLE SKYBLOCK MODE RECIPES)
Servers can add the pinned file to have skyblock mode automatically enabled without clients needing to change anything

**Comment by CarlSmotricz** [comment]
That was... impressively helpful, thanks a lot!

**Comment by LotP1** [comment]
np :) fyi we use the discord server because it allows us to keep track of all our packs in 1 central location

**Comment by CarlSmotricz** [comment]
To summarize, here's how I set up a server under Linux where my character, upon entering, found himself on a skyblock:

- Start with installing server package from CurseMod

- Once the server is running and past the EULA question, kill the server process.
NOTE: `jps` doesn't show it, so use `ps ux`. There's the server process (`forge.xxx.jar`) and the server runner (`serverstarter.xxx.jar`) which keeps restarting it and is sometimes resistant to `kill`.

- Edit server.properties to contain
`level-type=skyblockbuilder\:custom_skyblock`
`level-name=`<some new name, not the one that's (maybe) already created by the previous server run>

- Ensure that the top server directory (i.e. Techopolis) contains a file `skyblockMode.json` with the following contents:
```
{
        "enableSkyblockMode": true,
        "message": "True enables skyblock mode recipes."
}
```
